create table packs(
	id serial not null,
	pack_name text,
	base_deck boolean,
	info text,
	PRIMARY KEY (id)
);


create table white_cards(
	id serial not null,
	content text,
	watermark text,
	pack int,
	PRIMARY KEY (id),
	FOREIGN KEY (pack) REFERENCES packs(id) MATCH SIMPLE
);

create table black_cards(
	id serial not null,
	content text, 
	cards_required int,
	draw int,
	watermark text,
	pack int,
	PRIMARY KEY (ID),
	FOREIGN KEY (pack) REFERENCES packs(id) MATCH SIMPLE
);



INSERT INTO packs (id, pack_name, base_deck, info) values (1,'First Version', true, 'This is a testing deck');
INSERT INTO packs (id, pack_name, base_deck, info) values (2,'Second Version', true, 'This is a testing deck');
INSERT INTO packs (id, pack_name, base_deck, info) values (3,'Canadian', false, 'This is a testing deck');
INSERT INTO packs (id, pack_name, base_deck, info) values (4,'The First Expansion', false, 'This is a testing deck');
INSERT INTO packs (id, pack_name, base_deck, info) values (5,'The Second Expansion', false, 'This is a testing deck');


INSERT INTO white_cards (content, watermark,pack) values ('Michelle Obama''s arms.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('White people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An erection that lasts longer than four hours.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Panda sex.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Stifling a giggle at the mention of Hutus and Tutsis.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A middle-aged man on roller skates.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Coat hanger abortions.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Scrubbing under the folds.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Wearing underwear inside-out to avoid doing laundry.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dropping a chandelier on your enemies and riding the rope up.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Public ridicule.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A snapping turtle biting the tip of your penis.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Vehicular manslaughter.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The token minority.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('German dungeon porn.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Praying the gay away.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dying.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Same-sex ice dancing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dying of dysentery.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Roofies.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Big Bang.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Amputees.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Men.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Concealing a boner.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Agriculture.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Making a pouty face.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('YOU MUST CONSTRUCT ADDITIONAL PYLONS.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hormone injections.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tom Cruise.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Object permanence.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Consultants.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being marginalized.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The profoundly handicapped.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Party poopers.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Nickelback.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Doing the right thing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The invisible hand.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Heteronormativity.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cuddling.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Raptor attacks.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Fear itself.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sniffing glue.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An icepick lobotomy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being rich.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The clitoris.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sexy pillow fights.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Michael Jackson.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sexting.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Horse meat.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hunting accidents.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A cartoon camel enjoying the smooth, refreshing taste of a cigarette.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Abstinence.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mountain Dew Code Red.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tweeting.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Making sex at her.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Stunt doubles.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Flavored condoms.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Heath Ledger.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Muzzy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sunshine and rainbows.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Flash flooding.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Goblins.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Spectacular abs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Three-Fifths compromise.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Vigorous jazz hands.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Skeletor.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Vikings.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Genital piercings.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A really cool hat.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An Oedipus complex.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Underground Railroad.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Heartwarming orphans.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cheating in the Special Olympics.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sharing needles.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Ethnic cleansing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Eating all of the cookies before the AIDS bake-sale.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My humps.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The violation of our most basic human rights.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Fingering.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The placenta.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Flightless birds.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Stranger danger.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Chivalry.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sean Penn.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A sad handjob.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Jew-fros.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Self-loathing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A falcon with a cap on its head.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Historically black colleges.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Aaron Burr.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Former President George W. Bush.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Geese.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mutually-assured destruction.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bling.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Smegma.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The South.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pretending to care.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Arnold Schwarzenegger.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A sausage festival.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Foreskin.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being a dick to children.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Chainsaws for hands.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A Gypsy curse.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Pope.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A balanced breakfast.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Elderly Japanese men.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pictures of boobs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Science.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A bleached asshole.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Autocannibalism.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('William Shatner.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A micropenis.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Waterboarding.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bingeing and purging.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A clandestine butt scratch.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Man meat.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Laying an egg.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An honest cop with nothing left to lose.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The terrorists.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Friends who eat all the snacks.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cookie Monster devouring the Eucharist wafers.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Letting yourself go.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A LAN party.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A grande sugar-free iced soy caramel macchiato.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Will Smith.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Marky Mark and the Funky Bunch.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dave Matthews Band.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Substitute teachers.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Garth Brooks.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Keeping Christ in Christmas.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('That one gay Teletubby.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Passive-agression.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The People''s Elbow.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Guys who don''t call.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('AIDS.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Rapture.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Eugenics.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Taking off your shirt.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A drive-by shooting.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Ronald Reagan.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Jewish fraternities.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('All-you-can-eat shrimp for $4.99.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Scalping.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Edible underpants.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Figgy pudding.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Intelligent design.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Nocturnal emissions.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Uppercuts.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The American Dream.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Testicular torsion.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The folly of man.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The KKK.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The taint; the grundle; the fleshy fun-bridge.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Saxophone solos.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('That thing that electrocutes your abs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Oversized lollipops.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Friends with benefits.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Teaching a robot to love.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Me time.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The heart of a child.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Smallpox blankets.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Yeast.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Full frontal nudity.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Authentic Mexican cuisine.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Licking things to claim them as your own.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Genghis Khan.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The hardworking Mexican.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('RoboCop.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Spontaneous human combustion.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Natural selection.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A good sniff.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Nipple blades.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Leaving an awkward voicemail.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Assless chaps.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sweet, sweet vengeance.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Keg stands.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Darth Vader.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Necrophilia.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Toni Morrison''s vagina.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Preteens.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A cooler full of organs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Keanu Reeves.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A thermonuclear detonation.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A moment of silence.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Catapults.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Emotions.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Balls.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Homeless people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Old-people smell.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Farting and walking away.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The inevitable heat death of the universe.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Rev. Dr. Martin Luther King, Jr.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sperm whales.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A murder most foul.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Daddy issues.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Britney Spears at 55.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Natalie Portman.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Holy Bible.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pulling out.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pixelated bukkake.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Waiting ''til marriage.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The World of Warcraft.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Global warming.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('World peace.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A can of whoop-ass.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A zesty breakfast burrito.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Picking up girls at the abortion clinic.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Land mines.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('College.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A time travel paradox.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Seppuku.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Waking up half-naked in a Denny''s parking lot.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Christopher Walken.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Gloryholes.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A tiny horse.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Child abuse.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Menstruation.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A sassy black woman.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Re-gifting.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Penis envy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Drinking alone.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hulk Hogan.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Whipping it out.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dental dams.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Gandhi.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('God.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Friction.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A sea of troubles.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Poor people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Flesh-eating bacteria.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dick Cheney.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Lockjaw.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Take-backsies.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Opposable thumbs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The homosexual agenda.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Fiery poops.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cards Against Humanity.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sean Connery.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The milk man.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Chinese gymnastics team.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Eating the last known bison.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Soiling oneself.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Giving 110%.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Friendly fire.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Count Chocula.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Feeding Rosie O''Donnell.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Seduction.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being a motherfucking sorcerer.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Eastern European Turbo-Folk music.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Douchebags on their iPhones.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The deformed.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Donald Trump.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('This answer is postmodern.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('African children.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Have some more kugel.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Crippling debt.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Shorties and blunts.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('(I am doing Kegels right now.)',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bestiality.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Drum circles.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Inappropriate yelling.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Thong Song.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A vajazzled vagina.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tiger Woods.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('PCP.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mr. Snuffleupagus.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A disappointing birthday party.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Puppies!',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A windmill full of corpses.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being on fire.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A lifetime of sadness.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pterodactyl eggs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Crumpets with the Queen.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Exchanging pleasantries.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Republicans.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Kim Jong-il.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Glenn Beck being harried by a swarm of buzzards.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A salty surprise.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Jews.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Incest.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Nazis.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Repression.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Attitude.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Passable transvestites.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Puberty.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Swooping.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A look-see.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Lactation.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pabst Blue Ribbon.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The gays.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A foul mouth.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A hot mess.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My collection of high-tech sex toys.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bees?',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Getting drunk on mouthwash.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The glass ceiling.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sarah Palin.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Team-building exercises.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Frolicking.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Not giving a shit about the Third World.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My relationship status.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Barack Obama.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mouth herpes.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Wiping her butt.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pedophiles.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Doin''it in the butt.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Being fabulous.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An M. Night Shyamalan plot twist.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A bag of magic beans.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dead parents.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My sex life.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Riding off into the sunset.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dick fingers.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Virginia Tech Massacre.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Queefing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tangled Slinkys.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Civilian casualties.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Leprosy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Grave robbing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tentacle porn.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bill Nye the Science Guy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('New Age music.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('72 virgins.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hope.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Passing a kidney stone.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A mime having a stroke.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Classist undertones.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A mating display.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Kool-Aid Man.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Not reciprocating oral sex.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Date rape.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Italians.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My soul.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A stray pube.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Jerking off into a pool of children''s tears.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Getting really high.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Too much hair gel.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Overcompensation.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Free samples.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Shaquille O''Neal''s acting career.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Half-assed foreplay.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Explosions.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('White privilege.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Road head.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Poorly-timed Holocaust jokes.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('8 oz. of sweet Mexican black-tar heroin.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Judge Judy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Altar boys.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Scientology.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Justin Bieber.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Alcoholism.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('My genitals.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Winking at old people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Golden showers.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Racism.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Auschwitz.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Raping and pillaging.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Kids with ass cancer.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hurricane Katrina.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Lumberjack fantasies.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('American Gladiators.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('An asymmetric boob job.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Asians who aren''t good at math.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Loose lips.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Blood of Christ.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A brain tumor.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Prancing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Hamburglar.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Police brutality.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Forgetting the Alamo.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Booby-trapping the house to foil burglars.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Estrogen.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A robust mongoloid.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Her Royal Highness, Queen Elizabeth II.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Pooping back and forth. Forever.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cockfights.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bitches.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Stephen Hawking talking dirty.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Those times when you get sand in your vagina.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Faith healing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Impotence.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Bananas in Pajamas.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Getting so angry that you pop a boner.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Tasteful sideboob.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Two midgets shitting into a bucket.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Racially-biased SAT questions.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Glenn Beck catching his scrotum on a curtain hook.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The forbidden fruit.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Anal beads.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Surprise sex!',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dead babies.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Masturbation.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Hustle.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Obesity.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Child beauty pageants.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Goats eating coins.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Kamikaze pilots.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Powerful thighs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A big hoopla about nothing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Women''s suffrage.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('John Wilkes Booth.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Parting the Red Sea.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Harry Potter erotica.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Grandma.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Porn stars.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A monkey smoking a cigar.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mathletes.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Lance Armstrong''s missing testicle.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Children on leashes.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Multiple stab wounds.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Oompa-Loompas.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Peeing a little bit.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The miracle of childbirth.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Another goddamn vampire movie.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Active listening.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A gassy antelope.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('BATMAN!!!',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Black people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Serfdom.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Trail of Tears.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Ghosts.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Dance of the Sugar Plum Fairy.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Finger painting.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Robert Downey, Jr.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Muhammed (Praise Be Unto Him).',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Famine.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('AXE Body Spray.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Force.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Cybernetic enhancements.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Mr. Clean, right behind you.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Third base.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dwarf tossing.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A fetus.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Women in yogurt commercials.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Copping a feel.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sexual tension.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Dry heaving.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Centaurs.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Wifely duties.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hot people.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Kanye West.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Amish.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('When you fart and a little bit comes out.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Viagra&reg;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Twinkies&reg;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Five-Dollar Footlongs&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Tempur-Pedic&reg; Swedish Sleep System&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Fancy Feast&reg;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Hot Pockets&reg;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A neglected Tamagotchi&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Domino''s&trade; Oreo&trade; Dessert Pizza.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The &Uuml;bermensch.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Adderall&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Sobbing into a Hungry-Man&reg; Frozen Dinner.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Ring Pops&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('GoGurt&reg;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('A Super Soaker&trade; full of cat pee.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('Lunchables&trade;.',null,1);
INSERT INTO white_cards (content, watermark,pack) values ('The Make-A-Wish&reg; Foundation.',null,1);



INSERT INTO white_cards(content, watermark,pack) values ('Michelle Obama''s arms.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('White people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An erection that lasts longer than four hours.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Panda sex.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Stifling a giggle at the mention of Hutus and Tutsis.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A middle-aged man on roller skates.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Coat hanger abortions.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Scrubbing under the folds.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Wearing underwear inside-out to avoid doing laundry.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('MechaHitler.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Getting naked and watching Nickelodeon.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Charisma.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Morgan Freeman''s voice.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Breaking out into song and dance.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Soup that is too hot.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Chutzpah.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Unfathomable stupidity.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Horrifying laser hair removal accidents.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Boogers.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Expecting a burp and vomiting on the floor.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A defective condom.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Teenage pregnancy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hot cheese.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A mopey zoo lion.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Shapeshifters.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Care Bear Stare.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Erectile dysfunction.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The chronic.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('"Tweeting."',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Firing a rifle into the air while balls deep in a squealing hog.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Nicolas Cage.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dropping a chandelier on your enemies and riding the rope up.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Public ridicule.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A snapping turtle biting the tip of your penis.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Vehicular manslaughter.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The token minority.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A gentle caress of the inner thigh.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Poor life choices.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Embryonic stem cells.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Customer service representatives.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Little Engine That Could.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lady Gaga.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A death ray.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Vigilante justice.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Exactly what you''d expect.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Natural male enhancement.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Passive-aggressive Post-it notes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Inappropriate yodeling.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A homoerotic volleyball montage.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Actually taking candy from a baby.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Jibber-jabber.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Crystal meth.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My inner demons.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pac-Man uncontrollably guzzling cum.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My vagina.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The true meaning of Christmas.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Flying sex snakes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('German dungeon porn.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Praying the gay away.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dying.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Same-sex ice dancing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dying of dysentery.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Roofies.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Big Bang.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Amputees.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Men.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Concealing a boner.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Agriculture.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Making a pouty face.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('YOU MUST CONSTRUCT ADDITIONAL PYLONS.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hormone injections.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Tom Cruise.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Object permanence.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Consultants.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being marginalized.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The profoundly handicapped.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Party poopers.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Nickelback.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Doing the right thing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The invisible hand.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Heteronormativity.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Cuddling.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Raptor attacks.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Fear itself.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sniffing glue.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An icepick lobotomy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being rich.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The clitoris.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sexy pillow fights.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Michael Jackson.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sexting.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Horse meat.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sunshine and rainbows.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Flash flooding.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Goblins.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Spectacular abs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Three-Fifths compromise.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Vigorous jazz hands.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Skeletor.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Vikings.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Genital piercings.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A really cool hat.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An Oedipus complex.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Underground Railroad.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Heartwarming orphans.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Cheating in the Special Olympics.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sharing needles.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Ethnic cleansing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Eating all of the cookies before the AIDS bake-sale.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My humps.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The violation of our most basic human rights.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Fingering.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The placenta.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Flightless birds.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Stranger danger.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Chivalry.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sean Penn.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A sad handjob.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Jew-fros.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Self-loathing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A falcon with a cap on its head.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Historically black colleges.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Aaron Burr.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Former President George W. Bush.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Geese.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Mutually-assured destruction.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Bling.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Smegma.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The South.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pretending to care.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Arnold Schwarzenegger.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A sausage festival.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Foreskin.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being a dick to children.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Chainsaws for hands.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A Gypsy curse.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Pope.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A balanced breakfast.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Elderly Japanese men.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pictures of boobs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Science.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A bleached asshole.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Autocannibalism.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('William Shatner.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A micropenis.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Waterboarding.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Bingeing and purging.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A clandestine butt scratch.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Man meat.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Laying an egg.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An honest cop with nothing left to lose.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The terrorists.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Friends who eat all the snacks.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Guys who don''t call.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('AIDS.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Rapture.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Eugenics.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Taking off your shirt.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A drive-by shooting.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Ronald Reagan.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Jewish fraternities.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('All-you-can-eat shrimp for $4.99.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Scalping.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Edible underpants.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Figgy pudding.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Intelligent design.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Nocturnal emissions.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Uppercuts.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The American Dream.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Testicular torsion.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The folly of man.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The KKK.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The taint; the grundle; the fleshy fun-bridge.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Saxophone solos.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('That thing that electrocutes your abs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Oversized lollipops.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Friends with benefits.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Teaching a robot to love.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Me time.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The heart of a child.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Smallpox blankets.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Yeast.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Full frontal nudity.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Authentic Mexican cuisine.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Licking things to claim them as your own.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Genghis Khan.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The hardworking Mexican.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('RoboCop.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Spontaneous human combustion.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Natural selection.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A good sniff.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Nipple blades.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Leaving an awkward voicemail.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Assless chaps.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sweet, sweet vengeance.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Keg stands.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Darth Vader.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Necrophilia.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Toni Morrison''s vagina.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Preteens.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A cooler full of organs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Keanu Reeves.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A thermonuclear detonation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A moment of silence.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Catapults.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Emotions.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Balls.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Homeless people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Old-people smell.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Farting and walking away.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The inevitable heat death of the universe.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Rev. Dr. Martin Luther King, Jr.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sperm whales.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A murder most foul.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Daddy issues.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Britney Spears at 55.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Natalie Portman.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Holy Bible.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pulling out.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pixelated bukkake.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Waiting ''til marriage.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The World of Warcraft.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Global warming.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('World peace.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A can of whoop-ass.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A zesty breakfast burrito.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Picking up girls at the abortion clinic.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Land mines.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('College.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A time travel paradox.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Seppuku.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Waking up half-naked in a Denny''s parking lot.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Christopher Walken.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Gloryholes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A tiny horse.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Child abuse.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Menstruation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A sassy black woman.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Re-gifting.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Penis envy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Drinking alone.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hulk Hogan.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Whipping it out.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dental dams.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Gandhi.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('God.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Friction.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A sea of troubles.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Poor people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Flesh-eating bacteria.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dick Cheney.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lockjaw.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Take-backsies.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Opposable thumbs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The homosexual agenda.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Fiery poops.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Cards Against Humanity.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sean Connery.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The milk man.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Chinese gymnastics team.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Eating the last known bison.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Soiling oneself.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Giving 110%.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Friendly fire.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Count Chocula.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Feeding Rosie O''Donnell.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Seduction.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being a motherfucking sorcerer.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A disappointing birthday party.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Puppies!',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A windmill full of corpses.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being on fire.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A lifetime of sadness.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pterodactyl eggs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Crumpets with the Queen.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Exchanging pleasantries.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Republicans.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Kim Jong-il.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Glenn Beck being harried by a swarm of buzzards.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A salty surprise.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Jews.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Incest.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Nazis.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Repression.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Attitude.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Passable transvestites.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Puberty.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Swooping.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A look-see.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lactation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pabst Blue Ribbon.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The gays.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A foul mouth.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A hot mess.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My collection of high-tech sex toys.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Bees?',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Getting drunk on mouthwash.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The glass ceiling.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sarah Palin.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Team-building exercises.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Frolicking.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Not giving a shit about the Third World.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My relationship status.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Barack Obama.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Mouth herpes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Wiping her butt.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pedophiles.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Doin'' it in the butt.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Being fabulous.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An M. Night Shyamalan plot twist.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A bag of magic beans.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dead parents.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My sex life.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Riding off into the sunset.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dick fingers.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Virginia Tech Massacre.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Queefing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Tangled Slinkys.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Civilian casualties.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Leprosy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Grave robbing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Tentacle porn.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Bill Nye the Science Guy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('New Age music.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('72 virgins.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hope.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Passing a kidney stone.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A mime having a stroke.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Classist undertones.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A mating display.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Kool-Aid Man.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Not reciprocating oral sex.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Date rape.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Italians.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My soul.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A stray pube.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Jerking off into a pool of children''s tears.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Getting really high.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Too much hair gel.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Overcompensation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Free samples.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Shaquille O''Neal''s acting career.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Half-assed foreplay.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Explosions.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('White privilege.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Road head.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Poorly-timed Holocaust jokes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('8 oz. of sweet Mexican black-tar heroin.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Judge Judy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Altar boys.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Scientology.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Justin Bieber.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Alcoholism.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('My genitals.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Winking at old people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Golden showers.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Racism.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Auschwitz.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Raping and pillaging.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Kids with ass cancer.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hurricane Katrina.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lumberjack fantasies.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('American Gladiators.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('An asymmetric boob job.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Asians who aren''t good at math.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Loose lips.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Blood of Christ.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A brain tumor.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Prancing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Hamburglar.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Police brutality.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Forgetting the Alamo.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Booby-trapping the house to foil burglars.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Estrogen.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A robust mongoloid.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Her Royal Highness, Queen Elizabeth II.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Pooping back and forth. Forever.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Cockfights.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Bitches.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Stephen Hawking talking dirty.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Getting so angry that you pop a boner.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Tasteful sideboob.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Two midgets shitting into a bucket.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Racially-biased SAT questions.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Glenn Beck catching his scrotum on a curtain hook.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The forbidden fruit.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Anal beads.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Surprise sex!',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dead babies.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Masturbation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Hustle.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Obesity.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Child beauty pageants.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Goats eating coins.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Kamikaze pilots.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Powerful thighs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A big hoopla about nothing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Women''s suffrage.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('John Wilkes Booth.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Parting the Red Sea.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Harry Potter erotica.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Grandma.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Porn stars.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A monkey smoking a cigar.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Mathletes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lance Armstrong''s missing testicle.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Children on leashes.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Multiple stab wounds.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Oompa-Loompas.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Peeing a little bit.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The miracle of childbirth.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Another goddamn vampire movie.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Active listening.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A gassy antelope.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('BATMAN!!!',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Black people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Serfdom.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Trail of Tears.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Ghosts.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Dance of the Sugar Plum Fairy.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Finger painting.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Robert Downey, Jr.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Muhammed (Praise Be Unto Him).',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Famine.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('AXE Body Spray.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Force.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Cybernetic enhancements.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Mr. Clean, right behind you.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Third base.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dwarf tossing.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A fetus.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Women in yogurt commercials.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Copping a feel.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Sexual tension.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Dry heaving.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Centaurs.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Wifely duties.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hot people.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Kanye West.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Amish.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('When you fart and a little bit comes out.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Viagra&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Five-Dollar Footlongs&trade;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Tempur-Pedic&reg; Swedish Sleep System&trade;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Fancy Feast&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Hot Pockets&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Domino''s&trade; Oreo&trade; Dessert Pizza.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The &Uuml;bermensch.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Adderall&trade;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('GoGurt&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A Super Soaker&trade; full of cat pee.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Lunchables&trade;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Make-A-Wish&reg; Foundation.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('A Bop It&trade;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Home video of Oprah sobbing into a Lean Cuisine&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Euphoria&trade; by Calvin Klein.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('Switching to Geico&reg;.',null,2);
INSERT INTO white_cards(content, watermark,pack) values ('The Donald Trump Seal of Approval&trade;.',null,2);